application:
  security:
    oauth:
      registrar-client-secret: ${REGISTRAR_CLIENT_SECRET}
server:
  port: 9000
  forward-headers-strategy: NATIVE
spring:
  application:
    name: auth-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migrations
