app:
  oauth2:
    client:
      oidc-client:
        id: ${OIDC_CLIENT_ID}
        secret: ${OIDC_CLIENT_SECRET}
      registrar-client:
        id: ${REGISTRAR_CLIENT_ID}
        secret: ${REGISTRAR_CLIENT_SECRET}
  oidc:
    user:
      admin-user:
        username: ${ADMIN_USER_USERNAME}
        password: ${ADMIN_USER_PASSWORD}
server:
  port: 9000
  forward-headers-strategy: NATIVE
spring:
  application:
    name: auth-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migrations
